export const BrowserMessageTypes = {
    GetProjectNames: 'GetProjectNames',
    ProjectNames: 'ProjectNames',
    GetProject: 'GetProject',
    Project: 'Project',
    OpenFile: 'OpenFile',
    CreateWebsite: 'CreateWebsite',
    CreatePageType: 'CreatePageType',
    CreateComponentType: 'CreateComponentType',
    UpdateWebsite: 'UpdateWebsite',
    UpdatePageInstance: 'UpdatePageInstance',
    UpdateComponentInstance: 'UpdateComponentInstance',
    AddComponentInstance: 'AddComponentInstance',
    DeleteComponentInstance: 'DeleteComponentInstance',
    MatchUrl: 'MatchUrl',
};
